apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: tasks
  POSTGRES_PASSWORD: change-me-lab-only
  POSTGRES_DB: tasks
  DATABASE_URL: postgresql+psycopg2://tasks:change-me-lab-only@postgres:5432/tasks